### PR TITLE
bring in sync with upstream fakemetrics

### PR DESCRIPTION
**Pull request by Dieterbe**
pull in changes / best practices from upstream fakemetrics.in particular v2 aka MetricPoint support.
corresponding PR for fakemetrics: https://github.com/raintank/fakemetrics/pull/19
These 2 PR's makes the 2 codebases identical again, such that they can be merged.

### CODE REVIEW

**Comment by Dieterbe** [comment]
i don't seem to have broken it :)
```
~/g/s/g/g/m/s/t/chaos_cluster ❯❯❯ go test -v .                                                                                                                                               ⏎
2019-11-15 20:08:38.253 [INFO] stopping docker-chaos stack should it be running...
2019-11-15 20:08:53.556 [INFO] docker-compose version 1.24.1, build unknown
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

2019-11-15 20:08:53.556 [INFO] launching docker-chaos stack...
=== RUN   TestClusterStartup
2019-11-15 20:09:20.163 [INFO] stack now running.
2019-11-15 20:09:20.163 [INFO] Go to http://localhost:3000 (and login as admin:admin) to see what's going on
--- PASS: TestClusterStartup (26.61s)
=== RUN   TestClusterBaseIngestWorkload
--- PASS: TestClusterBaseIngestWorkload (11.56s)
=== RUN   TestQueryWorkload
--- PASS: TestQueryWorkload (60.00s)
=== RUN   TestIsolateOneInstance
--- PASS: TestIsolateOneInstance (60.02s)
PASS
2019-11-15 20:11:31.753 [INFO] stopping docker-compose stack...
2019-11-15 20:11:42.414 [INFO] docker-compose stack is shut down
ok  	github.com/grafana/metrictank/stacktest/tests/chaos_cluster	184.167s
```

**Comment by replay** [comment]
If they are that similar, why don't we directly `import` one into the other instead of copying the code?

**Comment by Dieterbe** [comment]
after these PR's is merged, that is the goal.

**Comment by replay** [comment]
Ok, so there is not really a point in reviewing this code you added in this PR in detail, right? because we already know that in the next step we're going to replace it again and it has already been reviewed when it was merged into `fakemetrics`.

**Comment by Dieterbe** [comment]
correct

**Pull request merged**
