### PR TITLE
use pointslicepool for /getdata cluster-fan out requests

### PR DESCRIPTION
**Pull request by Dieterbe**
Note: this builds on top of #1923, review/merge that first.

when handling a user query, fanning out said query, and reading back the /getdata responses from peers, this will use the pointslicepool to decode incoming point slices into and should reduce memory usage. see #962 

for review purposes, the generated code is identical except for the calls to pointslicepool.GetMin instead of `make`

### CODE REVIEW

**Comment by Dieterbe** [comment]
NOTE: i'm still working on some tests to confirm improvements

**Comment by Dieterbe** [comment]
here are the 3 different PSP behaviors
first one suffers from the nudging bug, which the 2nd one fixes. but we only do half the gets on the pool as puts because upon decoding we always allocate fresh.
only for q3 do we pull the same rate in and out of the pool. with the occassional miss which i presume is due to GC
psp

**Review by robert-milan — COMMENTED** [review]
Why do we need to manually maintain Series msgp encoding / decoding etc... ?

**Comment by Dieterbe** [comment]
because we use custom code to use the slice pool. perhaps it can be done cleaner with the msgp extension system but i didn't want to spend too much time on it.

**Review by robert-milan — APPROVED** [review]
LGTM

**Pull request merged**
