### PR TITLE
Initial import of raintank/fakemetrics

### PR DESCRIPTION
**Pull request by fitzoh**
Copy Paste contents of https://github.com/raintank/fakemetrics to `cmd/fakemetrics`.

Not sure if this layout is what makes the most sense, but it seemed like a reasonable starting point.
If nothing else this can serve as a starting point for a conversation.  Does not touch/address the fakemetrics code living in `stacktest/fakemetrics`

There's a whole lot of diff here, recommend reviewing commit by commit.

### CODE REVIEW

**Comment by replay** [comment]
This currently is not very integrated with the remaining tools yet, because it's not prefixed by `mt-`. 
F.e. if the resulting binary were prefixed with `mt-` like the other tools, then the CI checks would require its docs to be part of `docs/tools.md`, which I think would make sense. So to fix that we should either rename it to `mt-fakemetrics` or update the CI checks so they don't only look for stuff that's prefixed with `mt-`. 
IMHO naming it `mt-fakemetrics` is easier and makes it more consistent with all the other tools. 

By grepping you can see that quite many checks assume that tools as prefixed with `mt-`:

```
replay@mst-nb:~/go/src/github.com/grafana/metrictank/scripts$ ack mt-
build_docker.sh
17:    docker build -t grafana/mt-gateway --target=mt-gateway -f ${DIR}/Dockerfile .
18:    docker tag grafana/mt-gateway grafana/mt-gateway:$tag
19:    docker tag grafana/mt-gateway grafana/mt-gateway:$version

config/mt-gateway.ini
8:#mt-whisper-importer-writer address

dev/tools-to-doc.sh
21:for tool in mt-*; do

Dockerfile
15:# mt-gateway image #
17:FROM alpine:3.10.0 AS mt-gateway
21:COPY scripts/config/mt-gateway.ini /etc/metrictank/mt-gateway.ini
22:COPY --from=gobase /tmp/build/mt-gateway /usr/bin/
26:ENTRYPOINT ["/usr/bin/mt-gateway"]

push/extra-qa.sh
17:     res=$(curl -q https://mt-qa.grafana.net/try -d secret=$MTQA_SECRET -d version=$version)

push/dockerhub.sh
22:echo "### docker push grafana/mt-gateway:$version"
25:docker push grafana/mt-gateway:$version
28:echo "### docker push grafana/mt-gateway:$tag"
31:docker push grafana/mt-gateway:$tag

build_packages.sh
39:cp ${BUILD_ROOT}/{metrictank,mt-*} ${BUILD}/usr/bin/
70:cp ${BUILD_ROOT}/{metrictank,mt-*} ${BUILD}/usr/bin/
102:cp ${BUILD_ROOT}/{metrictank,mt-*} ${BUILD}/usr/bin/
132:cp ${BUILD_ROOT}/{metrictank,mt-*} ${BUILD}/usr/bin/
161:cp ${BUILD_ROOT}/{metrictank,mt-*} ${BUILD}/usr/bin/
```

**Comment by replay** [comment]
LGTM. 
We'll also need to figure out what to do with the `Dockerfile`, `README` and `make.sh` in that directory. 
Probably the `README` could somehow be integrated into the rest of the documentation. 
The `Dockerfile` shouldn't be necessary anymore because when the MT image is now built in the normal way then it also comes with `mt-fakemetrics`, so if somebody needs a docker image with fakemetrics they can just use the MT image.
When the `Dockerfile` isn't there anymore, then we also won't need the `make.sh`.

Do you think those changes should better be in a separate PR? If you think so then I'm also fine merging it once the tests pass

**Comment by fitzoh** [comment]
>Do you think those changes should better be in a separate PR? If you think so then I'm also fine merging it once the tests pass

Ended up just throwing them in here.  Nuked most of the other files in `cmd/mt-fakemetrics`, README still exists, but has been reduced substantially

**Review by replay — APPROVED** [review]
LGTM

**Pull request merged**
