### PR TITLE
Regen for test check

### PR DESCRIPTION
**Pull request by shanson7**
Looks like some optimizations were added for msgp generated code. This caused a test to fail on another PR I was working and I figured I'd put in a smaller quick PR to get it fixed.

### CODE REVIEW

**Comment by shanson7** [comment]
Note: this is all generated code

**Comment by shanson7** [comment]
There is a check that generated files match after a fresh generation. See https://circleci.com/gh/grafana/metrictank/6443?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by shanson7** [comment]
@replay can we merge this? I'm seeing other PR branches with these changes that are going to conflict. They can rebase off this once merged.

**Comment by replay** [comment]
@shanson7 sorry that it took a while, I assumed that once I approve it you'll be able to do the merge

**Comment by shanson7** [comment]
Apparently I cannot :/

**Pull request merged**
