### PR TITLE
first version of contribution guidelines

### PR DESCRIPTION
**Pull request by Dieterbe**

### CODE REVIEW

**Comment by Dieterbe** [comment]
@shanson7 do you have thoughts on this?

**Comment by shanson7** [comment]
Seems reasonable and easy enough to follow. What about linting / formatting code tools?

**Comment by Dieterbe** [comment]
good point, see new version.

**Comment by shanson7** [comment]
LGTM

**Comment by Dieterbe** [comment]
thanks for the feedback guys. and feel free to always suggest changes or additions.

**Pull request merged**
