### PR TITLE
Make summarize() output canonical in the !alignToFrom case

### LINKED ISSUE #1811: Incorrect normalization causes panic
**Describe the bug**

Relevant stack:
```
/metrictank/expr/seriesaggregators.go:147 (0xbc58bd)
/metrictank/expr/func_aggregate.go:74 (0xb98a3d)
/metrictank/expr/func_aggregate.go:61 (0xb97fea)
/metrictank/expr/plan.go:309 (0xbc4dcb)
/metrictank/api/graphite.go:844 (0xc39bf4)
/metrictank/api/graphite.go:268 (0xc32d0e)
```

I was able to narrow the crash down to a query like `sum(a, summarize(a, '10min'))`, where the lcm used to normalize is 600 (e.g. interval of a is a factor of 600). It seems that summarize adds in an extra datapoint at the beginning (pre-marking, as graphite does) so it has an extra datapoint after normalization.

It seems that perhaps summarize should be following almost identical logic to `normalizeTo` (with some exception for the `alignToFrom` case). This would result in postmarked result, but would be compatible for all later normalization.

### LINKED ISSUE #1845: panic on query like `asPercent(summarize(#A, '1min'), #A)`
**Describe the bug**
* launch docker-dev
* in Grafana, run this query against MT
```
#A stats.docker-env.response.200 (hidden)
#B asPercent(summarize(#A, '1min'), #A)
```

this results in a panic/http500:
```
<html> <head><title>PANIC: runtime error: index out of range [30] with length 30</title> <meta charset="utf-8" /> <style type="text/css"> html, body { font-family: "Roboto", sans-serif; color: #333333; background-color: #ea5343; margin: 0px; } h1 { color: #d04526; background-color: #ffffff; padding: 20px; border-bottom: 1px dashed #2b3848; } pre { margin: 20px; padding: 20px; border: 2px solid #2b3848; background-color: #ffffff; white-space: pre-wrap; /* css-3 */ white-space: -moz-pre-wrap; /* Mozilla, since 1999 */ white-space: -pre-wrap; /* Opera 4-6 */ white-space: -o-pre-wrap; /* Opera 7 */ word-wrap: break-word; /* Internet Explorer 5.5+ */ } </style> </head>
<body>
 <h1>PANIC</h1> <pre style="font-weight: bold;">runtime error: index out of range [30] with length 30</pre> <pre>/usr/lib/go/src/runtime/panic.go:88 (0x4326e2) 
$GOPATH/src/github.com/grafana/metrictank/expr/func_aspercent.go:221 (0xb8b6bb) 
$GOPATH/src/github.com/grafana/metrictank/expr/func_aspercent.go:90 (0xb880bb) 
$GOPATH/src/github.com/grafana/metrictank/expr/plan.go:309 (0xbae7f7) 
$GOPATH/src/github.com/grafana/metrictank/api/graphite.go:851 (0xc20597) 
$GOPATH/src/github.com/grafana/metrictank/api/graphite.go:270 (0xc19773)
/usr/lib/go/src/reflect/value.go:460 (0x4b6eca)
/usr/lib/go/src/reflect/value.go:321 (0x4b63d3) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0xab1dab) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0xab1789) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xc07691) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/raintank/gziper/gzip.go:100 (0xc07684) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:79 (0xacc490) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:157 (0xab1ad7) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:135 (0xab1878) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xadd0f5) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/recovery.go:161 (0xadd0e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/logger.go:40 (0xad0053) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:157 (0xab1ad7) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:135 (0xab1878) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xb31520) 
$GOPATH/src/github.com/grafana/metrictank/api/middleware/logger.go:45 (0xb31509)
/usr/lib/go/src/reflect/value.go:460 (0x4b6eca)
/usr/lib/go/src/reflect/value.go:321 (0x4b63d3) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0xab1dab) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0xab1789) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xb32dab) 
$GOPATH/src/github.com/grafana/metrictank/api/middleware/tracer.go:70 (0xb32d96) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:79 (0xacc490) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:157 (0xab1ad7) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:135 (0xab1878) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xb3248d) 
$GOPATH/src/github.com/grafana/metrictank/api/middleware/stats.go:76 (0xb32478) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:79 (0xacc490) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:157 (0xab1ad7) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:135 (0xab1878) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:112 (0xadd0f5) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/recovery.go:161 (0xadd0e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/logger.go:40 (0xad0053) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:157 (0xab1ad7) 
$GOPATH/src/github.com/grafana/metrictank/vendor/github.com/go-macaron/inject/inject.go:135 (0xab1878) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/context.go:121 (0xacc5e8) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:187 (0xade306) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/router.go:294 (0xad876d) 
$GOPATH/src/github.com/grafana/metrictank/vendor/gopkg.in/macaron.v1/macaron.go:220 (0xad138a)
/usr/lib/go/src/net/http/server.go:2807 (0x742792)
/usr/lib/go/src/net/http/server.go:1895 (0x73e20b)
/usr/lib/go/src/runtime/asm_amd64.s:1373 (0x467780) </pre> 
</body> </html>"
message:"Internal Server Error"
```

**Helpful Information**
Metrictank Version: v0.13.1-800-g74ba401c

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #1811
fix #1845

### CODE REVIEW

**Comment by Dieterbe** [comment]
well, alignToFrom is essentially an opt-in to turn your series into something that looks unlike anything else in metrictank. You'll likely run into panics when trying to comebine alignToFrom-summarized series with other series (as in #1811 and #1845) , which by the way, wouldn't make any sense if the timestamps aren't aligned. For this reason, I don't think it's worthwhile to spend on trying to "solve" something that doesn't seem to make any sense. If anything, I would rather discourage or deprecate use of this parameter.

Yes, the UX is not great, a clearer error would be better than a lowlevel panic (and we could do it for example by validating the plan to check for this bad usage, as explained in my comment in 1811) but so far i haven't seen any evidence of people trying to use summarize with alignToFrom *and* trying to combine that series with something else. So I think our engineering resources are better spent on other things.

**Comment by shanson7** [comment]
Fair points. Ultimately it would be better to have a clear error so the user knows how to solve it, but at this point it seems ok to.

**Comment by robert-milan** [comment]
Overall I like this PR. It is a straight-forward and simple solution which solves the problem. I also agree with Dieter's statements about alignToFrom. Maybe we should look into deprecating it.

**Comment by shanson7** [comment]
Deprecating alignToFrom? I think the use cases would need to be outlined before we consider that. There are valid cases that are difficult or impossible to do without it that would need valid replacements.

However, I do agree that normalization with other series that are not created using the same parameters does not make sense and can be an error case.

**Comment by Dieterbe** [comment]
> e.g. If you want to guarantee that you consolidate a series to a single datapoint, then you can do summarize(..., '10y', 'sum',alignToFrom=true) (where 10y is an arbitrary long time range). Useful for tables/singlestat where you want a real average, not the average of averages.

oh my. talk about a hack :) I think this is more commonly achieved by `consolidateBy(...,'sum')&maxDataPoints=1`, which is also not very elegant.

I think ideally the render api should have a set of functions to reduce timeseries into single points

**Comment by shanson7** [comment]
> oh my. talk about a hack :) I think this is more commonly achieved by consolidateBy(...,'sum')&maxDataPoints=1, which is also not very elegant.

No...not at all. If you want to sum the dividend and divisors before divideSeries, `consolidateBy` is useless as it happens too late.

**Comment by Dieterbe** [comment]
Ah, that is a good point. But I still find this a contorted use of the alignToFrom and interval parameters. Not obvious to anyone but Graphite wizards.
Would rather provide first class support for reducing series to single points. This could be an interesting new project.

**Comment by shanson7** [comment]
> Would rather provide first class support for reducing series to single points

That is exactly my point. I don't think this is a good thing, it's just as I said above:
> There are valid cases that are difficult or impossible to do without it that would need valid replacements.

I'm just pointing out that we shouldn't deprecate an existing API without very good rationale and thought put into it.

> This could be an interesting new project.

For sure. There are a lot of functions/behaviors of graphite that don't play nicely with each other (bound to happen with the sheer number of functions).

**Comment by Dieterbe** [comment]
Yeah, all good. I think we're on the same page. :+1: the examples you listed are valid, and I appreciate you coming up with them, cause I wouldn't have thought of them myself. I wonder if the first one could also be solved using the `tz` parameter, but i have no time right now to look into it. It's probably a viz-only flag.

I think another valid use case for alignToFrom is:

3. any time you run a job/task at a custom schedule and you want to align with that. (e.g. some cleanup worker, or marketing emails that go out a certain time,e tc)

**Pull request merged**
