### PR TITLE
update changelog

### PR DESCRIPTION
**Pull request by Dieterbe**
documenting an important caveat wrt cluster mode upgrades

### CODE REVIEW

**Comment by Dieterbe** [comment]
> Do we need to add the commit we are referencing?

I don't understand. we don't reference any commits ?

> How do people know what unreleased/master refers to after we start adding more commits?

it always refers to master, and we currently have no guarantee that changelog.md is perfectly up to date.

**Comment by woodsaj** [comment]
> I don't understand. we don't reference any commits ?

There were 184 commits between the last "release" and the commit that added the query nodes.  So there are already likely lots of MT instances that are already running a "master/unreleased" build that doesnt have updated handling of peer partitions needed for query nodes.  Without a reference to the commit that introduced the change (v0.11.0-184-g293b55b9) they may assume that because they are running "master/unstable" they already have the updated code.

**Comment by Dieterbe** [comment]
Up until now, the (unwritten) philosophy has been "if you deploy releases, you have an accurate changelog listing relevant changes and warning about any hazards; if you deploy from master, it's up to you to check the the git log and the work-in-progress changelog if there is one". I.e. we currently don't promise correct instructions until we cut a release.

Our choices are:
1) stick with this philosophy, but we can document it better
2) become more accommodating to people deploying from master. this would require enforcing that any PR merged that deserves a changelog mention (breaking or non-breaking), comes with the changelog.md updated included. This is annoying because when the code is finished locally and ready to file the PR, you don't know yet which pr number it'll be or which commit it'll be merged as.
3) We can perhaps find a happy medium: like 2 but only for PR's introducing breaking changes, include a basic changelog entry that mentions the breaking changes but not the commit/pr number, and then we fill in the pr number when we prepare the release. that way anyone deploying master will at least be warned, even though they may have to resort to the git log or closed PR view to get all the details.

As we do have people installing from master - and in fact we recommend it - I think 3 seems like the best option. Thoughts?

**Comment by robert-milan** [comment]
I agree that a mix of `2` and `3` sounds good. We can always update the changelog in a separate PR after this original is merged too. For breaking changes we should be letting people know. I think this is in line with better documentation.

**Comment by Dieterbe** [comment]
I have pushed the change reflective of what we discussed in yesterday's meeting.

**Comment by Dieterbe** [comment]
PTAL so i can merge

**Pull request merged**
