### PR TITLE
Update Graphite tags models to include From and To fields

### PR DESCRIPTION
**Pull request by carrieedwards**
This PR updates the GraphiteTags and GraphiteAutoCompleteTags models to include a FromTo field. This will enable the tags query to include from and to fields. This is part of changes necessary for an issue in which no tags will appear in the UI if metrics have not been ingested in the last hour

Related PR: 
- Grafana main repo: https://github.com/grafana/grafana/pull/41319

### CODE REVIEW

**Comment by Dieterbe** [comment]
Does graphite upstream use these parameters too?

Note that we keep a list of differences between metrictank and graphite at docs/graphite.md (this may need to be updated)
and also we keep our http api documentation in docs/http-api.md (will certainly need an update)

**Comment by robert-milan** [comment]
You will probably need to run `go generate ./...`, other than that I think it is fine.

**Comment by shanson7** [comment]
It seems like this adds the fields but they aren't used/respected in downstream code. Should they be?

**Comment by Dieterbe** [comment]
this is for GEM, which uses the same models and expr library.
In metrictank we don't actually use the fields, so we don't need to really update docs.
This could get a bit confusing, but I think it's fine.

**Comment by Dieterbe** [comment]
> You will probably need to run go generate ./..., other than that I think it is fine.

No change. probably because this is external api (towards users), not the internal api between metrictank nodes which uses messagepack

**Review by Dieterbe — APPROVED** [review]

**Pull request merged**
