### PR TITLE
Add support for `divideSeriesLists`

### PR DESCRIPTION
**Pull request by shanson7**

### CODE REVIEW

**Comment by Dieterbe** [comment]
do you think it would make sense to use the same implementation supporting both divideSeries and divideSeriesLists ? from the docs, looks like the only difference is whether the divisor is a single series or not. (i'm not saying that would be the better way, i'm happy to merge whichever approach you think is better)

**Comment by shanson7** [comment]
I did think about that, but was worried that handling the validation would get a little messy. Let me quickly mock up the approach and see what it looks like.

**Comment by Dieterbe** [comment]
yeah that was also my concern. sometimes it's better to have more code if it's simpler.
anyway don't spend too much time on that, i was more thinking out loud than anything.

**Comment by shanson7** [comment]
The logic to support iterating over the divisors in the list case is a little annoying, but the actual division and series creation stuff *could* be factored out into a shared implementation. I'm not sure where the best place to stick that would be.

**Pull request merged**
