### PR TITLE
Chunk 4h sparse bugfix longterm + remediation for single-point old format chunks

### PR DESCRIPTION
**Pull request by Dieterbe**
See #1126 for problem description and short term workaround.
This is the longer term fix: introducing a new chunk format. + implemented the remediation for chunks with a single point, as alluded to in #1126 

we now have:
* tsz.Series4h (the previous tsz.Series which should not be used for >4.5h spans and contains the read-time work around to recover from corruptions)
* tsz.SeriesLong : a similar format but it does not encode the initial t0 in the stream (because it's always tracked and persisted alongside the stream anyway, in our in memory structures as well as persisted in cassandra/bigtable), and it uses delta-of-delta from the get go, which supports arbitrary precision and is typically more compact for the first point than the necessary 17 bit encoding of the full timestamp we would have needed:
before storing any points, we assume an initial delta of 60,
if the delta happens to be 60, dod (delta-of-delta) is 0 so we store 1 bit.
if the dod is between -63 and 64 (e.g. delta is 1 to 120s) we only need to store '10' and a 7 bit value. so 9 bits.
for other cases and more info, see the paper. 
So the new format not only fixes the bug, it also saves us 32bit for the t0 and in most cases (14-9) to (14-1) (5 to 13 bits), by switching from a delta to dod for first point, shortening chunks by about 4 to 5 bytes.
it also uses a more compact end-of-stream marker, as explained in the devdocs, saving another up to 5bytes in the best case.

we then use SeriesLong everywhere in all new chunks, while old chunks can still be present in the database and chunk cache, so we accommodate for them by having each implement an iterator interface.  This does mean that getting points out of chunks comes with the interface overhead, but I think it shouldn't affect us much. on query heavy instances, a bit of increased cpu usage and maybe slightly slower responses. see the new benchmarks in tsz_test.go , though they don't match the results in https://github.com/Dieterbe/dataprocessexp , this can use a bit more research.

While doing this i also cleaned up some code, specifically in chunk.Chunk and chunk.IterGen, which are now cleaner and more focused.
Btw I want to rename IterGen to Chunk and Chunk could then be called "Block" or something, but perhaps I should do that in a followup PR.

### CODE REVIEW

**Comment by Dieterbe** [comment]
@robert-milan IterGen.Size() now returns slightly higher values than before (because it keeps the full chunk, not just the encoded tsz.Series data like before), and the type itself has a few different properties. IterGen.Size() is only called from the cache accounting. does anything need to change there in the cache accounting?

**Comment by Dieterbe** [comment]
did some race condition testing today, using the method described in https://github.com/grafana/metrictank/issues/1150#issuecomment-441728148  + running benchmarks/realistic-workload-single-tenant.sh (but with the mpo's and the vegeta rate divided by 20 otherwise my laptop couldn't hold it together - race builds are more resource intensive) , using docker-cluster which has 2min chunks, as to definitely have overlap between chunks getting saved and loaded, cache usage rising over time, etc.
while i found some other data races in memberlist and our index, nothing related to the changes here.

**Comment by Dieterbe** [comment]
reading data using mixed chunk formats works well.
```
MT_CASSANDRA_SCHEMA_FILE=scripts/config/schema-store-cassandra.toml ./mt-store-cat metric_4 1.63fc94941694d4e92f12b40ea6341eeb points | egrep 'chunk|Metric|Table'
2018-11-26 15:06:33.361 [INFO] cassandra_store: ensuring that keyspace metrictank exists.
## Metric 1.63fc94941694d4e92f12b40ea6341eeb(metrictank.stats.docker-dev-custom-cfg-kafka.default.process.resident_memory_bytes.gauge64)
### Table metric_4
number of chunks: 9
#### chunk 0 (t0:2018-11-26 14:48:00, span:120, format:FormatStandardGoTszWithSpan)
#### chunk 1 (t0:2018-11-26 14:50:00, span:120, format:FormatStandardGoTszWithSpan)
#### chunk 2 (t0:2018-11-26 14:52:00, span:120, format:FormatStandardGoTszWithSpan)
#### chunk 3 (t0:2018-11-26 14:54:00, span:120, format:FormatGoTszLongWithSpan)
#### chunk 4 (t0:2018-11-26 14:56:00, span:120, format:FormatGoTszLongWithSpan)
#### chunk 5 (t0:2018-11-26 14:58:00, span:120, format:FormatGoTszLongWithSpan)
#### chunk 6 (t0:2018-11-26 15:00:00, span:120, format:FormatGoTszLongWithSpan)
#### chunk 7 (t0:2018-11-26 15:02:00, span:120, format:FormatGoTszLongWithSpan)
#### chunk 8 (t0:2018-11-26 15:04:00, span:120, format:FormatStandardGoTszWithSpan)
```
(i tested both ways. when running master with the new format already in the database, requests fail obviously with unknown chunk format errors. but the new version displays data from both formats beautifully)

**Comment by Dieterbe** [comment]
Didn't mention it here yet, but last week I copied the broken chunks of the affected customer to a test environment and confirmed that i could accurately reproduce the incorrect viz of their rollup data using master (which was not being properly remediated due to having so many single-point chunks) , and that it was fixed with the code in this branch.

**Comment by Dieterbe** [comment]
## benchmarks: WIP

main concerns / areas of interest:

* increased cpu usage / latency due to iterator interface overhead. also slower cache due to itergens now having to do a bit more work to respond to EndTS(), Span() etc calls.
* increased memory usage for the remediations. note: when we have an intervalHint that is > 0, which only happens for aggregated (non-raw) archives, we have a very efficient remediation. in all other cases, we always clone the iterator and then try to see if we need to remediate. so the way to see any memory effect is by requesting raw data. we also have an extra field for the intervalHint.
on the flip side IterGen and Chunk have received some optimizations to use less memory.
* chunk size

to reproduce:
* disable cpu freq scaling etc
* spin up docker-dev-custom-cfg-kafka
* `./benchmarks/realistic-workload-single-tenant.sh` with tweaks

**Comment by Dieterbe** [comment]
```
BenchmarkPushSeries4h-8              	10000000	       188 ns/op
--- BENCH: BenchmarkPushSeries4h-8
    tsz_test.go:24: Series4h size: 19B
    tsz_test.go:24: Series4h size: 837B
    tsz_test.go:24: Series4h size: 82512B
    tsz_test.go:24: Series4h size: 8250012B
    tsz_test.go:24: Series4h size: 82500012B
BenchmarkPushSeriesLong-8            	10000000	       178 ns/op
--- BENCH: BenchmarkPushSeriesLong-8
    tsz_test.go:40: SeriesLong size: 10B
    tsz_test.go:40: SeriesLong size: 828B
    tsz_test.go:40: SeriesLong size: 82503B
    tsz_test.go:40: SeriesLong size: 8250003B
    tsz_test.go:40: SeriesLong size: 82500003B
```
==> 9 Bytes gain :sunglasses:

**Comment by Dieterbe** [comment]
I just went over all api endpoints and confirmed none of them returns a `chunk.IterGen` or any type that directly or indirectly contains one, so this confirms no serialization changes that may impact a running cluster.

**Comment by robert-milan** [comment]
> @robert-milan IterGen.Size() now returns slightly higher values than before (because it keeps the full chunk, not just the encoded tsz.Series data like before), and the type itself has a few different properties. IterGen.Size() is only called from the cache accounting. does anything need to change there in the cache accounting?

I didn't notice any changes in the structs we are using to estimate sizes, and since Size() itself is used for that particular calculation we should not need to change anything.

**Comment by Dieterbe** [comment]
ah yes, IterGen went from
```
type IterGen struct {
	B    []byte
	Ts   uint32
	Span uint32
}
```
to 
```
type IterGen struct {
        T0           uint32
        intervalHint uint32 
        B            []byte
}
```

lost the span, but need the intervalHint now (even for itergens that hold seriesLong data unless we want to wrap it in yet another interface, which i don't want). bummer :(

**Comment by Dieterbe** [comment]
for the record, just used benchstat to compare all go benchmarks before and after, and they're all identical

**Pull request merged**
