### PR TITLE
Refactor chaos dir to stacktest dir

### PR DESCRIPTION
**Pull request by Dieterbe**
* a bunch of refactoring / code-reorganisation of chaos dir which is now "stacktest" because it does both chaos testing as well as regular (see below), and adds a few more helper functions
* replace the python based end2end testing with the `stacktest/tests/end2end_carbon/end2end_carbon_test.go` file

### CODE REVIEW

**Comment by Dieterbe** [comment]
@replay what do you think of this?

**Comment by Dieterbe** [comment]
seems like in practice, the old code is faster on circleCI, even though on my computer new is about twice as fast  :8ball: 
https://circleci.com/gh/grafana/metrictank/3594 (master)
https://circleci.com/gh/grafana/metrictank/3589 (this)

to be clear, the speedup is supposed to come from the new approach being more eager (e.g. it'll retry the request until it gets a valid one, whereas the old approach just waits 30 seconds before checking)

**Comment by replay** [comment]
Seems ok. But what is actually the point of replacing the end2end test? isn't that just doing the same?

**Comment by Dieterbe** [comment]
there isn't a significant amount of point. that's why this also isn't high prio or anything, but I do think it's better that towards the future that all our different verification tooling converges on a set of standardized helper utilities for validating responses.
the speedup would also be nice, except it doesn't work on circleci yet

**Comment by Dieterbe** [comment]
update: makes sense to merge, especially now that the fakemetrics tool has seen a bunch of changes; with the old tooling, would need to somehow pin the fakemetrics binary to the exact right version, but with this code, it's trivial to assert that the tooling is in sync.
unfortunate that for some reason tearing down the docker-compose stack takes so long on circle, maybe we can solve that later.

**Pull request merged**
