### PR TITLE
Fix go generate qa check + update msgp to v1.1

### PR DESCRIPTION
**Pull request by Dieterbe**
We had newer generated code (with the new sentinel) but were vendoring the older library.
our qa check would compare against the older generated code, but didn't notice anything because it was executing `go generate` in the wrong dir.

### CODE REVIEW

**Comment by replay** [comment]
I'm not sure I understand the problem... When `Gopkg.Toml` specifies the version, and then we do `dep ensure`, this will put the correct specified version into the `vendor` dir, right? But then we also did `go get` in `go-generate.sh` which previously obtained the latest version, and that's the one we used to actually generate the library. Correct? And we didn't see that before because `go generate` was executed in the wrong dir and didn't change anything.

**Comment by woodsaj** [comment]
could we update go-generate.sh to read the revision number directly from Gopkg.lock and checkout out that commit?

**Comment by robert-milan** [comment]
I don't remember why right now, but there was a reason we didn't upgrade this last time. There is/was a breaking change when upgrading this library IIRC. I'll go try to find it.

**Comment by Dieterbe** [comment]
@woodsaj that's a great idea! pushing that now.
@robert-milan i was also wondering if there's a specific reason we haven't updated yet, i imagine there is one but i also couldn't find it.

**Comment by Dieterbe** [comment]
If no one can find the problem with the msgp library, can i get an approval on this?
Once I do, I'll update the schema dependency properly, which is currently causing the build failure.

**Comment by Dieterbe** [comment]
for the record, deployed this to our internal ops env today using an in-place upgrade.
both during, as well as after the upgrade, everything stayed nominal.

**Pull request merged**
