### PR TITLE
Upgrade dependency on gocql (will use later the fact that it includes a proper routing key for batches)

### PR DESCRIPTION
**Pull request by fkaleo**

### CODE REVIEW

**Comment by Dieterbe** [comment]
@fkaleo description of this PR please! what's going on here?

**Comment by fkaleo** [comment]
> @fkaleo description of this PR please! what's going on here?

it's all in the title really. it's only an upgrade of gocql to a newer version. it is generally useful to get more bugfixes and features. and in particular I would like to use at some point the fact that this newer version handles routing better when using batches.

**Comment by Dieterbe** [comment]
can you elaborate on "newer version handles routing better when using batches.". What exactly is this about? I don't see anything about routing in their git history.

**Comment by fkaleo** [comment]
> can you elaborate on "newer version handles routing better when using batches.". What exactly is this about? I don't see anything about routing in their git history.

IIRC that's the commit I needed:
https://github.com/gocql/gocql/commit/aa8c9ac52ff691706d36e9dd625d7bfb24053690

**Pull request merged**
