### PR TITLE
WIP: docker-cluster-relay stack with rules to feed back key metrics to customers

### PR DESCRIPTION
**Pull request by Dieterbe**
* requires https://github.com/graphite-ng/carbon-relay-ng/pull/161 to push stats from relay into kafka
* generally seems to work fine. though I'm still working on adding some more metrics and making sure things are correct. aggregating the too_old counters together is a bit tricky for example. will need to key the metrics differently and somehow add them together across all partitions (without adding the replicated ones), in a way that works with wraparounds.  seems like have to derive first, then use summing.
* aggregations currently configured with 1s buckets and 10s wait, meaning the relay waits 10s to finish off each aggregation point, in case a MT has trouble pushing its stats on time. this means stats come in with a 10 second delay
* the 2nd commit here also fixes an issue we've been having with the various docker stacks in general.  read the comments in https://github.com/raintank/metrictank/blob/df895407f4ed4f471efcc3631116bd1f17d470e7/docker/extra/populate-grafana.sh for an explanation.
* the carbon kafka route needs to know the orgid to publish the stats under. this is important when we deploy these configs.  (here i use -1 but in prod it should be the orgs' own id)

### CODE REVIEW

**Comment by Dieterbe** [comment]
on my laptop, with a very crude workload it looks like this: (note first a low volume, then i increased the fake load)
I also imported it to our production monitoring grafana to try it on a customer's setup, and there it looked good too.

**Comment by Dieterbe** [comment]
@woodsaj I think for you , to get this to production, you pretty much just need this line
```
     'addRoute kafkaMdm feedback regex=\.(input\.kafka-mdm\.metric.*|api\.request_handle|tank|cache|idx\.metrics_active)\.  kafka:9092 mdm snappy /conf/storage-schemas.conf byOrg -1',
```

this branch basically just lets us run that setup in dev so we can test it and/or make tweaks to the dashboard.  But it also has 1be9726729538fa6f05acfddb5f1a0665fac3059 which I'ld like to merge.

**Comment by woodsaj** [comment]
Thanks dieter,  once https://github.com/graphite-ng/carbon-relay-ng/pull/161 is merged ill update hosted-metrics-api to add a carbon-relay-ng per deployment that the metrics can flow via

**Comment by Dieterbe** [comment]
this isn't useful anymore
* our docker stacks have been reworked to provision via grafana provisioning (both dashboards and datasources)
* the rules in carbon-relay-ng.ini may be out of date. if we want to do this again, we should look at whatever the rules are we use in prod.
* instead of basic-stats.json we now have a hosted metrics summary dashboard that we give to our customers

if we need to create a new docker-cluster-relay stack in the future, it's fairly easy to do it again from scratch.
for the record:
```
diff -r docker/docker-cluster docker/docker-cluster-relay
Only in docker/docker-cluster-relay: basic-stats.json
Only in docker/docker-cluster-relay: carbon-relay-ng.ini
diff -r docker/docker-cluster/docker-compose.yml docker/docker-cluster-relay/docker-compose.yml
140a141,151
>   carbon-relay-ng:
>     hostname: carbon-relay-ng
>     image: raintank/carbon-relay-ng:latest
>     ports:
>      - "2003:2003"
>      - "2004:2004"
>      - "8081:8081"
>     volumes:
>      - "./carbon-relay-ng.ini:/conf/carbon-relay-ng.ini"
>      - "./storage-schemas.conf:/conf/storage-schemas.conf"
> 
146c157
<       - "2003:2003"
---
>       - "2003"
diff -r docker/docker-cluster/metrictank.ini docker/docker-cluster-relay/metrictank.ini
122c122
< addr = graphitemon:2003
---
> addr = carbon-relay-ng:2003
diff -r docker/docker-cluster/statsdaemon.ini docker/docker-cluster-relay/statsdaemon.ini
4c4
< graphite_addr = "graphitemon:2003"
---
> graphite_addr = "carbon-relay-ng:2003"
```

docker/docker-cluster-relay/carbon-relay-ng.ini (out of date now but mentioning anyway): 
```
instance = "default"

max_procs = 2

listen_addr = "0.0.0.0:2003"
pickle_addr = "0.0.0.0:2013"
admin_addr = "0.0.0.0:2004"
http_addr = "0.0.0.0:8081"
spool_dir = "/var/spool/carbon-relay-ng"
pid_file = "/var/run/carbon-relay-ng.pid"
#one of critical error warning notice info debug
log_level = "notice"
#log_level = "debug"
# How long to keep track of invalid metrics seen
# Useful time units are "s", "m", "h"
bad_metrics_max_age = "24h"
# Metric name validation strictness for legacy metrics. Valid values are:
# strict - Block anything that can upset graphite: valid characters are [A-Za-z0-9_-.]; consecutive dots are not allowed
# medium - Valid characters are ASCII; no embedded NULLs
# none   - No validation is performed
validation_level_legacy = "medium"
# Metric validation for carbon2.0 (metrics2.0) metrics.
# Metrics that contain = or _is_ are assumed carbon2.0.
# Valid values are:
# medium - checks for unit and mtype tag, presence of another tag, and constency (use = or _is_, not both)
# none   - No validation is performed
validation_level_m20 = "medium"

# you can also validate that each series has increasing timestamps
validate_order = false

# IMPORTANT: mixes stats from all metrictank environment and instances together and writes them to the same orgId.
# So this only works for dedicated single-org stacks.
init = [
     'addRoute sendAllMatch graphitemon  graphitemon:2003',
     'addRoute kafkaMdm feedback regex=\.(input\.kafka-mdm\.metric.*|api\.request_handle|tank|cache|idx\.metrics_active)\.  kafka:9092 mdm snappy /conf/storage-schemas.conf byOrg -1',
]

[instrumentation]
# in addition to serving internal metrics via expvar, you can optionally send em to graphite
graphite_addr = "localhost:2003" # feed back into the relay itself
graphite_interval = 1000  # in ms
```

**Pull request closed without merging**
