### PR TITLE
Feature fix name tag regex

### PR DESCRIPTION
**Pull request by shanson7**
This covers a corner case recently added with the special `name` tag.

### CODE REVIEW

**Comment by shanson7** [comment]
https://github.com/grafana/metrictank/pull/762/files?w=1 has a cleaner view of the changes (hides whitespace)

**Comment by replay** [comment]
Make sense to me :+1:

**Comment by Dieterbe** [comment]
can you update the commit message to convey what exactly the problem is that this solves.

**Comment by shanson7** [comment]
Message updated.

**Comment by Dieterbe** [comment]
thanks @shanson7 !

**Pull request merged**
