### PR TITLE
fix logger again

### PR DESCRIPTION
**Pull request by Dieterbe**
as of #823 / #825, the logger was created before flags were parsed
and the config (file and env vars) were loaded.
so the logger would always get the default value for the flag
and no way to change the level..
I tried creating the logger after flag parsing, and adjusting the log
level after config parsing, but couldn't the second step to work
properly.

Simplest solution is to just print to stderr directly the one time we
actually need it in between the two steps.

PS: I hate this logging library, but we'll get rid of it. see #624

### CODE REVIEW

**Comment by Dieterbe** [comment]
cc @Spellchaser FYI

**Comment by Spellchaser** [comment]
So the logger gets the default value from the [init function](https://github.com/grafana/metrictank/blob/master/cmd/metrictank/metrictank.go#L81-L83). Are you saying that 
> adjusting the log level after config parsing

 doesn't work [here](https://github.com/grafana/metrictank/blob/master/cmd/metrictank/metrictank.go#L154-L169)?

I think I opted to use the logger rather than using `fmt` because it already had a default log level set.

**Comment by Dieterbe** [comment]
> I think I opted to use the logger rather than using fmt because it already had a default log level set.

problem with that is, it would use the default value from the flag definition in the init function. if you pass a custom flag, it wouldn't be applied because the flags get parsed after creating the logger.

there's various things wrong with the logging library we use. i couldn't get it to create a logger the first time (after flag parsing) and updating the level after checking the env vars/config file.

some usability problems with the library are detailed in https://github.com/grafana/grafana/issues/4055 and they are the cause of that code you link to; but i think neither of us should spend the time re-investigating them

i just wanted to loop you in to see if you saw something obviously wrong here. because eventually we're switching logging libraries anyway.

**Comment by Dieterbe** [comment]
Spellchaser4:01 PM
I think it’s fine. Since you plan to replace the logging mechanism anyway the quick fix works.

**Pull request merged**
