### PR TITLE
Remove promql

### LINKED ISSUE #1454: remove promql support
prometheus on top of metrictank has never really worked great, due to minor design differences between graphite and prometheus.
and our prometheus integration uses an old version of the library that results in vendoring conflicts when we want to use prometheus elsewhere (e.g. the instrumentation of the jaeger library), which is annoying
Since Cortex or Thanos are better solutions for prometheus users, we will remove the prometheus ingest/query functionality out of the metrictank platform.

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #1454

### CODE REVIEW

**Comment by fitzoh** [comment]
Should `input/prometheus` go away as well?

**Comment by Dieterbe** [comment]
yes. actually we should probably grep around a bit more too. there might be some documentation talking about prometheus too, that we should clean up.
do you mind continuing this ?
if you remove code, be sure to run `./scripts/qa/vendor.sh` and if needed `dep ensure` to clean up dependencies.

**Comment by fitzoh** [comment]
Think this is good to go aside from a changelog update

**Comment by Dieterbe** [comment]
looks great @fitzoh . unfortunately i can't approve this PR because it's my own :)

**Review by fitzoh — APPROVED** [review]

**Pull request merged**
