### PR TITLE
groupByNode[s]: implement ordering like graphite does

### LINKED ISSUE #1767: groupByNodes() does not return series in a consistent order, Graphite does
When using `groupByNodes()` in Metrictank the order of the returned series is randomized because the order is determined by the order in which keys get read from this map, and Go randomizes the map key order:
https://github.com/grafana/metrictank/blob/487e2d4073ef0e5f332185c311e9988315a4e8ba/expr/func_groupbynodes.go#L73

In graphite the order is guaranteed to be the order in which keys got generated, to do this it is using a list here:
https://github.com/graphite-project/graphite-web/blob/4ce727593e949554cf1653ec7a42280a4b4578fd/webapp/graphite/render/functions.py#L4891

This can lead to issues if the return value of `groupByNodes()` is used as input for another function for which the order is relevant. We have observed a user who's using the output of `groupByNodes()` as input for `divideSeriesLists()`, which has lead to wrong results once we switched to Metrictank function processing.

### PR DESCRIPTION
**Pull request by Dieterbe**
fix #1767 

## PRE
pre

## POST
post

### CODE REVIEW

**Comment by Dieterbe** [comment]
cc @fqiu7

**Comment by replay** [comment]
LGTM but wouldn't it make sense to also update the unit tests so they check for the correct order?

**Comment by Dieterbe** [comment]
i don't like unit tests that are literally the same code as the code that is under test.

**Comment by fqiu7** [comment]
LGTM. I agree the ordering should be consistent.

**Comment by replay** [comment]
> i don't like unit tests that are literally the same code as the code that is under test.

I agree with that, but that's not how i would implement them. At the moment `testGroupByNodes()` just sorts the expected and the returned series before comparing. I'd remove that sorting and then make sure that the expected list of metrics is sorted as we expect it to be.

**Comment by Dieterbe** [comment]
@replay ah yes. we can simply assert that we got them in the same order as how they are specified in the tests, which we can achieve by simply removing the sorting. like this?

**Pull request merged**
